FROM ubuntu:16.04
MAINTAINER Keith McDuffee <keith@realistek.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
    percona-server-server-5.6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 3306

CMD ["/usr/bin/mysqld_safe"]
