FROM ubuntu:16.04
MAINTAINER Keith McDuffee <keith@realistek.com>

RUN apt-get update && apt-get install -y \
    samba && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN echo root:root | chpasswd

EXPOSE 139/tcp
EXPOSE 145/tcp
EXPOSE 137/udp
EXPOSE 138/udp

CMD ["/usr/sbin/smbd", "-F"]
