#!/bin/bash

# V1.1

EXT_IFACE=eth0
MEM_LIMIT=128M
SERVICE=22

QUOTA_IN=5242880
QUOTA_OUT=1310720

CPUSET_CPUS=1

READ_ONLY="--read-only"

{
    CNM="honeypot-ssh-${REMOTE_HOST}"

    # check if the container exists
    if ! /usr/bin/docker inspect "${CNM}" &> /dev/null; then
	# create new container
	SVR_HOSTNAME=live-svr-$(( ( RANDOM % 10 )  + 1 ))
	CID=$(/usr/bin/docker run -h ${SVR_HOSTNAME} ${READ_ONLY} -d --name ${CNM} -e "REMOTE_HOST=${REMOTE_HOST}" -m ${MEM_LIMIT} -d -i honeyfarm/ssh)
	CIP=$(/usr/bin/docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CID})
    else
	# start container if exited and grab the cid
        /usr/bin/docker start "${CNM}" &> /dev/null
        CID=$(/usr/bin/docker inspect --format '{{ .Id }}' "${CNM}")
	CIP=$(/usr/bin/docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CID})
    fi
} &> /dev/null

# forward traffic to the container
/usr/bin/socat -T300 stdin tcp:${CIP}:22,retry=5

# Destroy this container once they're disconnected or idle
/usr/bin/docker kill ${CID}
/usr/bin/docker rm ${CID}
